### Step1. Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Step2. Creating & Reading the data

In [10]:
df= pd.read_csv(r"C:\Users\shrey\OneDrive\Desktop\Imaritcus Notes\Machine Learning\Naive Bayes\mobile_price.csv",header=0)
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

### Step3. Data Exploration 

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [11]:
df.describe().T

count        mean          std    min      25%     50%  \
battery_power  2000.0  1238.51850   439.418206  501.0   851.75  1226.0   
blue           2000.0     0.49500     0.500100    0.0     0.00     0.0   
clock_speed    2000.0     1.52225     0.816004    0.5     0.70     1.5   
dual_sim       2000.0     0.50950     0.500035    0.0     0.00     1.0   
fc             2000.0     4.30950     4.341444    0.0     1.00     3.0   
four_g         2000.0     0.52150     0.499662    0.0     0.00     1.0   
int_memory     2000.0    32.04650    18.145715    2.0    16.00    32.0   
m_dep          2000.0     0.50175     0.288416    0.1     0.20     0.5   
mobile_wt      2000.0   140.24900    35.399655   80.0   109.00   141.0   
n_cores        2000.0     4.52050     2.287837    1.0     3.00     4.0   
pc             2000.0     9.91650     6.064315    0.0     5.00    10.0   
px_height      2000.0   645.10800   443.780811    0.0   282.75   564.0   
px_width       2000.0  1251.51550   432.199447  500.0   874.75  1247.0   
ram            2000.0  2124.21300  1084.732044  256.0  1207.50  2146.5   
sc_h           2000.0    12.30650     4.213245    5.0     9.00    12.0   
sc_w           2000.0     5.76700     4.356398    0.0     2.00     5.0   
talk_time      2000.0    11.01100     5.463955    2.0     6.00    11.0   
three_g        2000.0     0.76150     0.426273    0.0     1.00     1.0   
touch_screen   2000.0     0.50300     0.500116    0.0     0.00     1.0   
wifi           2000.0     0.50700     0.500076    0.0     0.00     1.0   
price_range    2000.0     1.50000     1.118314    0.0     0.75     1.5   

                   75%     max  
battery_power  1615.25  1998.0  
blue              1.00     1.0  
clock_speed       2.20     3.0  
dual_sim          1.00     1.0  
fc                7.00    19.0  
four_g            1.00     1.0  
int_memory       48.00    64.0  
m_dep             0.80     1.0  
mobile_wt       170.00   200.0  
n_cores           7.00     8.0  
pc               15.00    20.0  
px_height       947.25  1960.0  
px_width       1633.00  1998.0  
ram            3064.50  3998.0  
sc_h             16.00    19.0  
sc_w              9.00    18.0  
talk_time        16.00    20.0  
three_g           1.00     1.0  
touch_screen      1.00     1.0  
wifi              1.00     1.0  
price_range       2.25     3.0

### Step4. Check if there are missing values. If yes, handle them.

In [12]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

### Step5. Creating X & Y

In [16]:
X=df.values[:,:-1]
Y=df.values[:,-1]
Y=Y.astype(int)

In [18]:
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()

scaler.fit(X)

X= scaler.transform(X)

### Step6. Shuffle and Split Data

In [19]:
from sklearn.model_selection import train_test_split  #<1000=in range of 80-20  &  >1000=in range of 70-30

#Split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [22]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1600, 20)
(1600,)
(400, 20)
(400,)


In [20]:
from sklearn.naive_bayes import GaussianNB

model_NB= GaussianNB()

model_NB.fit(X_train,Y_train)

Y_pred= model_NB.predict(X_test)

print(list(zip(Y_test,Y_pred)))

[(3, 3), (3, 3), (2, 1), (3, 3), (1, 1), (3, 3), (3, 2), (3, 3), (1, 2), (3, 3), (2, 2), (3, 3), (0, 0), (1, 2), (0, 0), (3, 3), (2, 2), (3, 3), (2, 3), (2, 2), (3, 3), (2, 2), (0, 0), (1, 1), (0, 0), (0, 0), (3, 2), (3, 3), (1, 1), (1, 1), (2, 2), (0, 0), (3, 3), (2, 3), (2, 2), (2, 1), (1, 1), (1, 0), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (0, 0), (1, 1), (3, 3), (1, 2), (0, 1), (1, 1), (2, 1), (1, 1), (3, 3), (2, 3), (3, 3), (2, 2), (3, 3), (2, 2), (3, 3), (0, 0), (0, 0), (1, 1), (1, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (1, 1), (1, 2), (3, 3), (2, 2), (2, 2), (1, 0), (1, 1), (3, 3), (2, 1), (3, 3), (3, 3), (2, 2), (1, 1), (3, 3), (0, 0), (1, 1), (0, 0), (0, 0), (3, 3), (2, 2), (3, 3), (3, 3), (3, 3), (2, 2), (3, 3), (3, 3), (3, 3), (3, 3), (1, 2), (0, 0), (1, 1), (0, 1), (1, 1), (3, 3), (0, 0), (1, 1), (2, 2), (1, 2), (3, 3), (2, 1), (1, 1), (2, 2), (2, 2), (2, 1), (0, 0), (3, 3), (1, 2), (2, 1), (1, 1), (1, 1), (2, 1), (3, 3), (0, 0), (1, 1), (0, 1), (3, 3), (2, 2), (1, 1),

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[83  9  0  0]
 [ 7 69 21  0]
 [ 0 23 77  9]
 [ 0  0  6 96]]
Classification report:
              precision    recall  f1-score   support

           0       0.92      0.90      0.91        92
           1       0.68      0.71      0.70        97
           2       0.74      0.71      0.72       109
           3       0.91      0.94      0.93       102

    accuracy                           0.81       400
   macro avg       0.82      0.82      0.81       400
weighted avg       0.81      0.81      0.81       400

Accuracy of the model:  0.8125


In [27]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=50,
                                          random_state=10,bootstrap=True)
#n_jobs are use to priotize the current work

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)
Y_pred=model_RandomForest.predict(X_test)
#print(Y_pred)
print(list(zip(Y_test,Y_pred)))

[(3, 3), (3, 3), (2, 2), (3, 3), (1, 1), (3, 3), (3, 3), (3, 3), (1, 1), (3, 3), (2, 2), (3, 3), (0, 0), (1, 1), (0, 0), (3, 3), (2, 2), (3, 3), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (1, 1), (0, 0), (0, 0), (3, 2), (3, 3), (1, 1), (1, 1), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (2, 2), (1, 1), (1, 0), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (0, 0), (1, 0), (3, 3), (1, 2), (0, 0), (1, 1), (2, 1), (1, 1), (3, 3), (2, 2), (3, 2), (2, 3), (3, 3), (2, 2), (3, 3), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (1, 0), (1, 2), (3, 3), (2, 2), (2, 2), (1, 1), (1, 1), (3, 3), (2, 1), (3, 3), (3, 3), (2, 2), (1, 1), (3, 2), (0, 0), (1, 1), (0, 0), (0, 0), (3, 3), (2, 2), (3, 3), (3, 3), (3, 3), (2, 2), (3, 3), (3, 3), (3, 3), (3, 3), (1, 1), (0, 0), (1, 1), (0, 1), (1, 1), (3, 3), (0, 0), (1, 1), (2, 2), (1, 2), (3, 3), (2, 1), (1, 1), (2, 2), (2, 2), (2, 1), (0, 0), (3, 3), (1, 1), (2, 2), (1, 1), (1, 1), (2, 1), (3, 3), (0, 0), (1, 1), (0, 1), (3, 3), (2, 2), (1, 1),

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[86  6  0  0]
 [ 8 82  7  0]
 [ 0 15 85  9]
 [ 0  0  7 95]]
Classification report:
              precision    recall  f1-score   support

           0       0.91      0.93      0.92        92
           1       0.80      0.85      0.82        97
           2       0.86      0.78      0.82       109
           3       0.91      0.93      0.92       102

    accuracy                           0.87       400
   macro avg       0.87      0.87      0.87       400
weighted avg       0.87      0.87      0.87       400

Accuracy of the model:  0.87


In [32]:
print(list(zip(df.columns[:-1],model_RandomForest.feature_importances_)))

[('battery_power', 0.07514327772611443), ('blue', 0.006332625460223702), ('clock_speed', 0.02655690932654729), ('dual_sim', 0.006668883064342039), ('fc', 0.020493066509615288), ('four_g', 0.005610035471906587), ('int_memory', 0.03425167538830663), ('m_dep', 0.02293311154975105), ('mobile_wt', 0.03622643675272721), ('n_cores', 0.02252025948219726), ('pc', 0.026955651944311595), ('px_height', 0.05780610659444292), ('px_width', 0.05406274253644679), ('ram', 0.5057995345807775), ('sc_h', 0.02676930028334843), ('sc_w', 0.02567241863146879), ('talk_time', 0.0274691433730321), ('three_g', 0.005882629193725493), ('touch_screen', 0.006856172872020866), ('wifi', 0.0059900192586940125)]


In [34]:
new_df=df.drop(["blue","dual_sim","four_g","three_g","touch_screen","wifi"],axis=1)
new_df.shape

(2000, 15)

In [35]:
X=new_df.values[:,:-1]
Y=new_df.values[:,-1]
Y=Y.astype(int)

In [37]:
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()

scaler.fit(X)

X= scaler.transform(X)

In [38]:
from sklearn.model_selection import train_test_split  #<1000=in range of 80-20  &  >1000=in range of 70-30

#Split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [39]:
from sklearn.naive_bayes import GaussianNB

model_NB= GaussianNB()

model_NB.fit(X_train,Y_train)

Y_pred= model_NB.predict(X_test)

print(list(zip(Y_test,Y_pred)))

[(3, 3), (3, 3), (2, 1), (3, 3), (1, 1), (3, 3), (3, 3), (3, 3), (1, 2), (3, 3), (2, 2), (3, 3), (0, 0), (1, 2), (0, 0), (3, 3), (2, 2), (3, 3), (2, 3), (2, 2), (3, 3), (2, 2), (0, 0), (1, 1), (0, 0), (0, 0), (3, 2), (3, 3), (1, 1), (1, 1), (2, 2), (0, 0), (3, 3), (2, 3), (2, 2), (2, 1), (1, 1), (1, 0), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (0, 0), (1, 1), (3, 3), (1, 2), (0, 1), (1, 1), (2, 1), (1, 1), (3, 3), (2, 3), (3, 3), (2, 2), (3, 3), (2, 2), (3, 3), (0, 0), (0, 0), (1, 1), (1, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (1, 1), (1, 2), (3, 3), (2, 2), (2, 2), (1, 0), (1, 1), (3, 3), (2, 1), (3, 3), (3, 3), (2, 2), (1, 1), (3, 3), (0, 0), (1, 1), (0, 0), (0, 0), (3, 3), (2, 2), (3, 3), (3, 3), (3, 3), (2, 2), (3, 3), (3, 3), (3, 3), (3, 3), (1, 2), (0, 0), (1, 1), (0, 1), (1, 1), (3, 3), (0, 0), (1, 1), (2, 2), (1, 2), (3, 3), (2, 1), (1, 1), (2, 2), (2, 2), (2, 1), (0, 0), (3, 3), (1, 2), (2, 1), (1, 1), (1, 1), (2, 1), (3, 3), (0, 0), (1, 1), (0, 1), (3, 3), (2, 2), (1, 1),

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[83  9  0  0]
 [ 7 69 21  0]
 [ 0 22 77 10]
 [ 0  0  5 97]]
Classification report:
              precision    recall  f1-score   support

           0       0.92      0.90      0.91        92
           1       0.69      0.71      0.70        97
           2       0.75      0.71      0.73       109
           3       0.91      0.95      0.93       102

    accuracy                           0.81       400
   macro avg       0.82      0.82      0.82       400
weighted avg       0.81      0.81      0.81       400

Accuracy of the model:  0.815


In [43]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=100,
                                          random_state=10,bootstrap=True)
#n_jobs are use to priotize the current work

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)
Y_pred=model_RandomForest.predict(X_test)
#print(Y_pred)
print(list(zip(Y_test,Y_pred)))

[(3, 3), (3, 3), (2, 2), (3, 3), (1, 1), (3, 3), (3, 3), (3, 3), (1, 1), (3, 3), (2, 2), (3, 3), (0, 0), (1, 1), (0, 0), (3, 3), (2, 2), (3, 3), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (1, 1), (0, 0), (0, 0), (3, 2), (3, 3), (1, 1), (1, 1), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (2, 2), (1, 1), (1, 0), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (0, 0), (1, 0), (3, 3), (1, 2), (0, 0), (1, 1), (2, 1), (1, 1), (3, 3), (2, 2), (3, 2), (2, 3), (3, 3), (2, 2), (3, 3), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (2, 2), (0, 0), (2, 1), (1, 0), (1, 2), (3, 3), (2, 2), (2, 2), (1, 1), (1, 1), (3, 3), (2, 1), (3, 3), (3, 3), (2, 2), (1, 1), (3, 2), (0, 0), (1, 0), (0, 0), (0, 0), (3, 3), (2, 1), (3, 3), (3, 3), (3, 3), (2, 2), (3, 3), (3, 3), (3, 3), (3, 3), (1, 1), (0, 0), (1, 1), (0, 1), (1, 1), (3, 3), (0, 0), (1, 1), (2, 2), (1, 2), (3, 3), (2, 2), (1, 1), (2, 2), (2, 2), (2, 1), (0, 0), (3, 3), (1, 1), (2, 2), (1, 1), (1, 1), (2, 1), (3, 3), (0, 0), (1, 1), (0, 1), (3, 3), (2, 2), (1, 1),

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[85  7  0  0]
 [ 8 84  5  0]
 [ 0 13 91  5]
 [ 0  0  7 95]]
Classification report:
              precision    recall  f1-score   support

           0       0.91      0.92      0.92        92
           1       0.81      0.87      0.84        97
           2       0.88      0.83      0.86       109
           3       0.95      0.93      0.94       102

    accuracy                           0.89       400
   macro avg       0.89      0.89      0.89       400
weighted avg       0.89      0.89      0.89       400

Accuracy of the model:  0.8875
